### ISSUE TITLE
Runtime Crash using swift 4.2 compiler

### ISSUE THREAD

**Issue by PhilippeLandry-Logient** [Jibestream/JMap-iOS-SDK-Pod#1]
We had  runtime crashes with the app compiled using new swift 4.2 compiler.
Temporary FIX: we removed some "noescape" annotations from some objC header files (we don't use pod install)

example from JMapController.h:

- (void)showMap:(nonnull JMapMap *)map completionHandler:(__attribute__((noescape)) ErrorCompletion)completion;

becomes:

- (void)showMap:(nonnull JMapMap *)map completionHandler:(__attribute__(()) ErrorCompletion)completion;

**Comment by rhaidar** [comment]
@jibestreamdev close?

**Comment by PhilippeLandry-Logient** [comment]
It worked for me, many thanks!

**Comment by rhaidar** [comment]
@PhilippeLandry-Logient I had the same issue this morning but they updated the framework and that fixed it as well
